<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>GitHub Security Alert</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap');

  body {
    background-color: #f6f8fa;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
      Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    margin: 0;
    padding: 40px 0;
    display: flex;
    justify-content: center;
  }
  .container {
    background: #fff;
    border: 1px solid #d1d5da;
    border-radius: 6px;
    width: 420px;
    padding: 32px 24px;
    box-shadow: 0 1px 3px rgb(27 31 35 / 0.1);
  }
  .logo {
    display: flex;
    justify-content: flex-start;
    margin-bottom: 24px;
  }
  .logo svg {
    fill: #24292e;
    width: 32px;
    height: 32px;
  }
  h1 {
    font-weight: 600;
    font-size: 20px;
    color: #24292e;
    margin-bottom: 16px;
  }
  p {
    font-size: 15px;
    color: #24292e;
    margin-bottom: 20px;
    line-height: 1.4;
  }
  form input[type="text"], form input[type="password"] {
    width: 100%;
    padding: 12px 10px;
    margin-bottom: 16px;
    border: 1px solid #d1d5da;
    border-radius: 6px;
    box-sizing: border-box;
    font-size: 14px;
  }
  form button {
    width: 100%;
    background-color: #d73a49;
    border: none;
    padding: 12px;
    font-weight: 600;
    color: white;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
  }
  form button:hover {
    background-color: #b73140;
  }
  .footer {
    margin-top: 24px;
    font-size: 13px;
    color: #6a737d;
  }
  .footer a {
    color: #0366d6;
    text-decoration: none;
  }
  .footer a:hover {
    text-decoration: underline;
  }
</style>
</head>
<body>

<div class="container">
  <div class="logo" aria-label="GitHub">
    <!-- GitHub Mark SVG -->
    <svg viewBox="0 0 16 16" version="1.1" aria-hidden="true">
      <path fill-rule="evenodd"
        d="M8 0C3.58 0 0 3.58 0 8a8 8 0 005.47 7.59c.4.07.55-.17.55-.38 
        0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52
        -.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64
        -.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.22 2.2.82a7.57 7.57
        0 012 0c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87
        3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0016
        8c0-4.42-3.58-8-8-8z"></path>
    </svg>
  </div>

  <h1>Security Alert for your GitHub Account</h1>
  <p>
    Dear axel21062008,<br><br>
    We detected unusual activity on your GitHub account. To ensure your account's security, please verify your identity by logging in below within the next 24 hours.<br><br>
    Failure to do so may result in temporary suspension of your account.
  </p>

  <form id="verifyForm" onsubmit="return false;">
    <input type="text" name="login" placeholder="Username or email address" autocomplete="username" required>
    <input type="password" name="password" placeholder="Password" autocomplete="current-password" required>
    <button type="submit">Verify Account</button>
  </form>

  <div class="footer">
    <p>
      If you did not attempt to sign in, please <a href="https://github.com/support" target="_blank" rel="noopener">contact support</a>.
    </p>
  </div>
</div>

<script>
  document.getElementById('verifyForm').addEventListener('submit', function(e) {
    e.preventDefault();
    const login = this.login.value;
    const password = this.password.value;
    console.log('Identifiant saisi :', login);
    console.log('Mot de passe saisi :', password);
    alert('Thank you. Your account verification is complete.');
    // Ici on simule la réception des données, sans rien envoyer nulle part
  });
</script>

</body>
</html>
